services:
  redis:
    image: redis:7
    restart: unless-stopped
    ports:
      - "6379:6379"

  mongo:
    image: mongo:6.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    command: ["--bind_ip_all"]

  crawler:
    build:
      context: .
      dockerfile: Dockerfile.crawler
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - PORT=8081

  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://mongo:27017
      - CRAWLER_URL=http://crawler:8081/crawl
    depends_on:
      - redis
      - mongo
      - crawler

# Note: the Rust app is built from the local Dockerfile and will run as the `server` service.
# The integration script in `scripts/integration_test.sh` currently starts services and runs
# the app locally via `cargo run`; you can instead run `docker-compose up --build` to run
# everything in containers (including the server) if preferred.
